-- Adiciona campos de endereço à tabela 'profiles'
ALTER TABLE "public"."profiles" 
  ADD COLUMN IF NOT EXISTS "cep" TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS "estado" TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS "localidade" TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS "bairro" TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS "logradouro" TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS "numero" TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS "complemento" TEXT DEFAULT NULL; 